/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as p2PTradinSol from "./P2PTradin.sol";
export type { p2PTradinSol };
import type * as p2PTradingSol from "./P2PTrading.sol";
export type { p2PTradingSol };
export * as factories from "./factories";
export type { IERC20 } from "./P2PTradin.sol/IERC20";
export { IERC20__factory } from "./factories/P2PTradin.sol/IERC20__factory";
export type { P2PTrading } from "./P2PTradin.sol/P2PTrading";
export { P2PTrading__factory } from "./factories/P2PTradin.sol/P2PTrading__factory";
