/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace P2PTrading {
  export type OrderStruct = {
    orderId: BigNumberish;
    user: AddressLike;
    usdtAmount: BigNumberish;
    inrAmount: BigNumberish;
    isBuyOrder: boolean;
    isCompleted: boolean;
    isVerified: boolean;
    adminApproved: boolean;
    timestamp: BigNumberish;
    orderType: string;
  };

  export type OrderStructOutput = [
    orderId: bigint,
    user: string,
    usdtAmount: bigint,
    inrAmount: bigint,
    isBuyOrder: boolean,
    isCompleted: boolean,
    isVerified: boolean,
    adminApproved: boolean,
    timestamp: bigint,
    orderType: string
  ] & {
    orderId: bigint;
    user: string;
    usdtAmount: bigint;
    inrAmount: bigint;
    isBuyOrder: boolean;
    isCompleted: boolean;
    isVerified: boolean;
    adminApproved: boolean;
    timestamp: bigint;
    orderType: string;
  };
}

export interface P2PTradingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAdmin"
      | "admin"
      | "adminExecuteSellTransfer"
      | "approveOrder"
      | "authorizedAdmins"
      | "completeBuyOrder"
      | "completeSellOrder"
      | "confirmOrderReceived"
      | "createBuyOrder"
      | "createSellOrder"
      | "directSellTransfer"
      | "getAdminWallet"
      | "getOrder"
      | "getOrderCounter"
      | "orders"
      | "removeAdmin"
      | "usdtToken"
      | "verifyPayment"
      | "withdrawEmergency"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OrderCompleted"
      | "OrderCreated"
      | "OrderVerified"
      | "USDTTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "adminExecuteSellTransfer",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approveOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedAdmins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeBuyOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeSellOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmOrderReceived",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBuyOrder",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createSellOrder",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "directSellTransfer",
    values: [BigNumberish, BigNumberish, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdminWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEmergency",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adminExecuteSellTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedAdmins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeBuyOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeSellOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmOrderReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBuyOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSellOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "directSellTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAdminWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrderCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEmergency",
    data: BytesLike
  ): Result;
}

export namespace OrderCompletedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    user: AddressLike,
    usdtAmount: BigNumberish
  ];
  export type OutputTuple = [orderId: bigint, user: string, usdtAmount: bigint];
  export interface OutputObject {
    orderId: bigint;
    user: string;
    usdtAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    user: AddressLike,
    usdtAmount: BigNumberish,
    inrAmount: BigNumberish,
    isBuyOrder: boolean,
    orderType: string
  ];
  export type OutputTuple = [
    orderId: bigint,
    user: string,
    usdtAmount: bigint,
    inrAmount: bigint,
    isBuyOrder: boolean,
    orderType: string
  ];
  export interface OutputObject {
    orderId: bigint;
    user: string;
    usdtAmount: bigint;
    inrAmount: bigint;
    isBuyOrder: boolean;
    orderType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderVerifiedEvent {
  export type InputTuple = [orderId: BigNumberish, admin: AddressLike];
  export type OutputTuple = [orderId: bigint, admin: string];
  export interface OutputObject {
    orderId: bigint;
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace USDTTransferredEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    from: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    from: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface P2PTrading extends BaseContract {
  connect(runner?: ContractRunner | null): P2PTrading;
  waitForDeployment(): Promise<this>;

  interface: P2PTradingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAdmin: TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;

  admin: TypedContractMethod<[], [string], "view">;

  adminExecuteSellTransfer: TypedContractMethod<
    [
      _userAddress: AddressLike,
      _usdtAmount: BigNumberish,
      _inrAmount: BigNumberish,
      _orderType: string
    ],
    [void],
    "nonpayable"
  >;

  approveOrder: TypedContractMethod<
    [_orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  authorizedAdmins: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  completeBuyOrder: TypedContractMethod<
    [_orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  completeSellOrder: TypedContractMethod<
    [_orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confirmOrderReceived: TypedContractMethod<
    [_orderId: BigNumberish],
    [void],
    "view"
  >;

  createBuyOrder: TypedContractMethod<
    [_usdtAmount: BigNumberish, _inrAmount: BigNumberish, _orderType: string],
    [void],
    "nonpayable"
  >;

  createSellOrder: TypedContractMethod<
    [_usdtAmount: BigNumberish, _inrAmount: BigNumberish, _orderType: string],
    [void],
    "nonpayable"
  >;

  directSellTransfer: TypedContractMethod<
    [
      _usdtAmount: BigNumberish,
      _inrAmount: BigNumberish,
      _orderType: string,
      _adminWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getAdminWallet: TypedContractMethod<[], [string], "view">;

  getOrder: TypedContractMethod<
    [_orderId: BigNumberish],
    [P2PTrading.OrderStructOutput],
    "view"
  >;

  getOrderCounter: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        bigint,
        string
      ] & {
        orderId: bigint;
        user: string;
        usdtAmount: bigint;
        inrAmount: bigint;
        isBuyOrder: boolean;
        isCompleted: boolean;
        isVerified: boolean;
        adminApproved: boolean;
        timestamp: bigint;
        orderType: string;
      }
    ],
    "view"
  >;

  removeAdmin: TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;

  usdtToken: TypedContractMethod<[], [string], "view">;

  verifyPayment: TypedContractMethod<
    [_orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawEmergency: TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "adminExecuteSellTransfer"
  ): TypedContractMethod<
    [
      _userAddress: AddressLike,
      _usdtAmount: BigNumberish,
      _inrAmount: BigNumberish,
      _orderType: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveOrder"
  ): TypedContractMethod<[_orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedAdmins"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "completeBuyOrder"
  ): TypedContractMethod<[_orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeSellOrder"
  ): TypedContractMethod<[_orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmOrderReceived"
  ): TypedContractMethod<[_orderId: BigNumberish], [void], "view">;
  getFunction(
    nameOrSignature: "createBuyOrder"
  ): TypedContractMethod<
    [_usdtAmount: BigNumberish, _inrAmount: BigNumberish, _orderType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSellOrder"
  ): TypedContractMethod<
    [_usdtAmount: BigNumberish, _inrAmount: BigNumberish, _orderType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "directSellTransfer"
  ): TypedContractMethod<
    [
      _usdtAmount: BigNumberish,
      _inrAmount: BigNumberish,
      _orderType: string,
      _adminWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAdminWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [_orderId: BigNumberish],
    [P2PTrading.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrderCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        bigint,
        string
      ] & {
        orderId: bigint;
        user: string;
        usdtAmount: bigint;
        inrAmount: bigint;
        isBuyOrder: boolean;
        isCompleted: boolean;
        isVerified: boolean;
        adminApproved: boolean;
        timestamp: bigint;
        orderType: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeAdmin"
  ): TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyPayment"
  ): TypedContractMethod<[_orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawEmergency"
  ): TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OrderCompleted"
  ): TypedContractEvent<
    OrderCompletedEvent.InputTuple,
    OrderCompletedEvent.OutputTuple,
    OrderCompletedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderVerified"
  ): TypedContractEvent<
    OrderVerifiedEvent.InputTuple,
    OrderVerifiedEvent.OutputTuple,
    OrderVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "USDTTransferred"
  ): TypedContractEvent<
    USDTTransferredEvent.InputTuple,
    USDTTransferredEvent.OutputTuple,
    USDTTransferredEvent.OutputObject
  >;

  filters: {
    "OrderCompleted(uint256,address,uint256)": TypedContractEvent<
      OrderCompletedEvent.InputTuple,
      OrderCompletedEvent.OutputTuple,
      OrderCompletedEvent.OutputObject
    >;
    OrderCompleted: TypedContractEvent<
      OrderCompletedEvent.InputTuple,
      OrderCompletedEvent.OutputTuple,
      OrderCompletedEvent.OutputObject
    >;

    "OrderCreated(uint256,address,uint256,uint256,bool,string)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderVerified(uint256,address)": TypedContractEvent<
      OrderVerifiedEvent.InputTuple,
      OrderVerifiedEvent.OutputTuple,
      OrderVerifiedEvent.OutputObject
    >;
    OrderVerified: TypedContractEvent<
      OrderVerifiedEvent.InputTuple,
      OrderVerifiedEvent.OutputTuple,
      OrderVerifiedEvent.OutputObject
    >;

    "USDTTransferred(uint256,address,address,uint256)": TypedContractEvent<
      USDTTransferredEvent.InputTuple,
      USDTTransferredEvent.OutputTuple,
      USDTTransferredEvent.OutputObject
    >;
    USDTTransferred: TypedContractEvent<
      USDTTransferredEvent.InputTuple,
      USDTTransferredEvent.OutputTuple,
      USDTTransferredEvent.OutputObject
    >;
  };
}
